<?php
namespace controllers;
use Ubiquity\attributes\items\router\Get;
use Ubiquity\attributes\items\router\Route;
use Ubiquity\attributes\items\router\Post;
 /**
  * Controller TodosController
  */
class TodosController extends ControllerBase{
    #[Route('_default',name: 'home')]
	public function index(){
		$this->displayList(['Pain','Eau']);
	}

	#[Post(path: "todos/add",name: 'todos.add')]
	public function addElement(){
		
	}


	#[Get(path: "todos/delete/{index}", name: 'todos.delete')]
	public function deleteElement($index){
		
	}


	#[Post(path: "todos/edit/{index}",name: 'todos.edit')]
	public function editElement($index){
		
	}


	#[Get(path: "todos/loadList/{uniqid}",name: 'todos.loadList')]
	public function loadList($uniqid){
		
	}


	
	private function menu(){
		
		$this->loadView('TodosController/menu.html');

	}

	public function initialize()
{
    parent::initialize(); // TODO: Change the autogenerated stub
    $this->menu();
}


	#[Get(path: "todos/new/{force}",name: 'dodos.new')]
	public function newList($force = false){
		
	}


	#[Get(path: "todos/saveList")]
	public function saveList(){
		
	}


	#[Post(path: "todos/loadList/")]
	public function loadListFromForm(){
		
	}


	
	private function displayList($list){
		
		$this->loadView('TodosController/displayList.html', ['list'=>$list]);

	}

}
